version: '3.4'

services:

  nerddinner-web:
    image: nerd-dinner/web
    ports:
      - "8020:80"
    env_file:
      - connection-strings.env
    depends_on:
      - nerddinner-db
    networks:
     - app-net

  nerddinner-db:
    image: nerd-dinner/db
    environment: 
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks: 
     - app-net
    
networks:
  app-net:
    external:
      name: nat
