version: '3.4'

services:

  nerddinner-web:
    image: nerd-dinner/web
    ports:
      - "8020:80"
    environment:
      - ConnectionStrings:NerdDinnerConnectionString=Server=nerddinner-db;Database=NerdDinner;
    depends_on:
      - nerddinner-db
    networks:
     - app-net

  nerddinner-db:
    image: nerd-dinner/db
    ports:
      - "1433:1433"
    environment:
     - ACCEPT_EULA=Y
    networks: 
     - app-net
    
networks:
  app-net:
    external:
      name: nat
