version: '3.4'

services:
  nerddinner:
    image: nerddinner:dev
    build:
      target: builder
    volumes:
      - C:\Users\nickik\Projects\windows-containers-demo\NET_Monolith_NerdDinner\NerdDinner:C:\inetpub\wwwroot
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"

